auditorsala:
    pattern:  /
    defaults: { _controller: "CademAdminBundle:Auditorsala:index" }

auditorsala_show:
    pattern:  /{id}/show
    defaults: { _controller: "CademAdminBundle:Auditorsala:show" }

auditorsala_new:
    pattern:  /new
    defaults: { _controller: "CademAdminBundle:Auditorsala:new" }

auditorsala_create:
    pattern:  /create
    defaults: { _controller: "CademAdminBundle:Auditorsala:create" }
    requirements: { _method: post }
    options:
        expose: true

auditorsala_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "CademAdminBundle:Auditorsala:edit" }

auditorsala_update:
    pattern:  /{id}/update
    defaults: { _controller: "CademAdminBundle:Auditorsala:update" }
    requirements: { _method: post|put }
    options:
        expose: true	

auditorsala_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "CademAdminBundle:Auditorsala:delete" }
    requirements: { _method: post|delete }
    options:
        expose: true	

auditorsala_body:
    pattern:  /body
    defaults: { _controller: "CademAdminBundle:Auditorsala:body" }
    requirements: { _method: get }
