salacliente:
    pattern:  /
    defaults: { _controller: "CademAdminBundle:Salacliente:index" }

salacliente_show:
    pattern:  /{id}/show
    defaults: { _controller: "CademAdminBundle:Salacliente:show" }

salacliente_new:
    pattern:  /new
    defaults: { _controller: "CademAdminBundle:Salacliente:new" }

salacliente_create:
    pattern:  /create
    defaults: { _controller: "CademAdminBundle:Salacliente:create" }
    requirements: { _method: post }

salacliente_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "CademAdminBundle:Salacliente:edit" }

salacliente_update:
    pattern:  /{id}/update
    defaults: { _controller: "CademAdminBundle:Salacliente:update" }
    requirements: { _method: post|put }

salacliente_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "CademAdminBundle:Salacliente:delete" }
    requirements: { _method: post|delete }
salacliente_body:
    pattern:  /body
    defaults: { _controller: "CademAdminBundle:Salacliente:body" }
    requirements: { _method: get }	
