parameters:
#    cadem_admin.example.class: Cadem\AdminBundle\Example

services:
#    cadem_admin.example:
#        class: %cadem_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    cadem_admin.authentication.login_success_handler:
        class: Cadem\AdminBundle\EventListener\LoginSuccessHandler
        arguments:  [@router, @security.context]
    cadem_admin.authentication.logout_handler:
        class: Cadem\AdminBundle\EventListener\LogoutHandler
        arguments:  []
